version: "3.1"
services:

  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pm
      POSTGRES_PASSWORD: pm123
      POSTGRES_DB: projectmanagement
    volumes:
      - /var/lib/postgresql/data


  projectmanagement-backend:
    image: projectmanagement-backend
    ports:
      - "8080:8080"
      - "4848:4848"
      - "8181:8181"
    volumes:
      - ./deployments:/opt/payara/deployments